stages:
  - build
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

project_build:
  stage: build
  only:
    - develop
    - master
  script:
    - pwd
    - composer install
    - npm install
    - npm run build
    - chmod 755 -R storage
  artifacts:
    paths:
      - ./
    expire_in: 10 mins

test_develop:
  stage: deploy
  only:
    - develop
  variables:
    HOST: $TEST_HOST
    USER: $TEST_USER
    PASSWORD: $TEST_PASSWORD
    APP_PATH: $TEST_APP_PATH
  script:
    - export SSHPASS=$PASSWORD

    - sshpass -e ssh $USER@$HOST -o StrictHostKeyChecking=no echo "SSH connection successful $USER, $HOST, $APP_PATH"
    - sshpass -e ssh $USER@$HOST -o stricthostkeychecking=no "
      rm -rf $APP_PATH/*
      "
    - sshpass -e scp -o stricthostkeychecking=no -r * $USER@$HOST:$APP_PATH
    - sshpass -e ssh $USER@$HOST -o stricthostkeychecking=no "
      cd $APP_PATH
      && rm -rf .env
      && touch .env
      && echo 'APP_NAME=\"$TEST_APP_NAME\"' >> .env
      && echo "APP_ENV=local" >> .env
      && echo "APP_KEY=" >> .env
      && echo "APP_DEBUG=true" >> .env
      && echo "APP_URL=$TEST_APP_URL" >> .env
      && echo "ASSET_URL=$TEST_APP_URL" >> .env
      && echo "APP_NAME=$TEST_APP_NAME" >> .env
      && echo "DB_CONNECTION=mysql" >> .env
      && echo "DB_HOST=localhost" >> .env
      && echo "DB_PORT=3306" >> .env
      && echo "DB_DATABASE=$TEST_DB_NAME" >> .env
      && echo "DB_USERNAME=$TEST_DB_USER" >> .env
      && echo "DB_PASSWORD=${TEST_DB_PASSWORD@Q}" >> .env
      && php8.3 artisan key:generate
      && cat .env
      && php8.3 artisan migrate --force
      && php8.3 artisan cache:clear
      && php8.3 artisan config:cache
      && php8.3 artisan route:cache
      "

atmo_deploy:
  stage: deploy
  only:
    - master
  variables:
    HOST: $ATMO_HOST
    USER: $ATMO_USER
    PASSWORD: $ATMO_PASSWORD
    APP_PATH: $ATMO_APP_PATH
  script:
    - export SSHPASS=$PASSWORD

    - sshpass -e ssh $USER@$HOST -o stricthostkeychecking=no "
      rm -rf $APP_PATH/*
      "
    - sshpass -e scp -o stricthostkeychecking=no -r * $USER@$HOST:$APP_PATH
    - sshpass -e ssh $USER@$HOST -o stricthostkeychecking=no "
      cd $APP_PATH
      && rm -rf .env
      && touch .env
      && echo 'APP_NAME=\"$ATMO_APP_NAME\"' >> .env
      && echo "APP_ENV=production" >> .env
      && echo "APP_KEY=" >> .env
      && echo "APP_DEBUG=false" >> .env
      && echo "APP_URL=$ATMO_APP_URL" >> .env
      && echo "ASSET_URL=$ATMO_APP_URL" >> .env
      && echo "APP_NAME=$ATMO_APP_NAME" >> .env
      && echo "DB_CONNECTION=mysql" >> .env
      && echo "DB_HOST=localhost" >> .env
      && echo "DB_PORT=3306" >> .env
      && echo "DB_DATABASE=$ATMO_DB_NAME" >> .env
      && echo "DB_USERNAME=$ATMO_DB_USER" >> .env
      && echo "DB_PASSWORD=${ATMO_DB_PASSWORD@Q}" >> .env
      && php8.3 artisan key:generate
      && cat .env
      && php8.3 artisan migrate --force
      && php8.3 artisan cache:clear
      && php8.3 artisan config:cache
      && php8.3 artisan route:cache
      "
